version: '3.1'
services:
  node-reback:
    container_name: node-reback
    volumes:
      - ./src:/app/src:ro
    env_file:
      - config/config.env
    ports:
      - 3000:3000
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    container_name: mongo-reback
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    env_file:
      - config/config.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo

  redis:
    image: redis
    container_name: redis-reback
    restart: always

  

volumes:
  mongo_data: