version: '3.1'
services:
  node-reback:
    container_name: node-reback
    volumes:
      - ./src:/app/src:ro
    env_file:
      - config/config.env
    ports:
      - 3000:3000
  
  mongo-reback:
    container_name: mongo-reback
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    env_file:
      - config/config.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: man
      MONGO_INITDB_ROOT_PASSWORD: qqq